version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_image:4
    networks:
      - network
    volumes:
      - static-volume:/home/SOYOLIM/staticfiles
      - media-volume:/home/SOYOLIM/media
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: chzhfflt0605
      MYSQL_DATABASE: django
      MYSQL_USER: soyolim
      MYSQL_PASSWORD: chzhfflt0605

networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-volume: